### ISSUE TITLE
Add docker compose setup

### ISSUE THREAD

**Issue by louisguitton** [louisguitton/dbt-metadata-utils#2]
Add docker-compose setup to ease the time of Windows users

- python base image runs `make update-git-metadata` with a volume for static files
- npm base image runs `npm build` like I do for github pages with a volume for static files
- nginx image serves static files from python and npm images 

kudos @larsjohanssonblank

**Comment by larsjohanssonblank** [comment]
Fantastic!
 I'll pull the code and try it out.
